# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy web-inlamningsuppgift3-we

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore
        working-directory: D:\a\Inlamningsuppgift3\Inlamningsuppgift3\Inlamning3

      - name: Build with dotnet
  
        run: dotnet build D:\a\Inlamningsuppgift3\Inlamningsuppgift3\Inlamning3 --configuration Release

      - name: dotnet publish
        run: dotnet publish D:\a\Inlamningsuppgift3\Inlamningsuppgift3\Inlamning3 -c Release -o D:\a\Inlamningsuppgift3\Inlamningsuppgift3\Inlamning3

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: D:\a\Inlamningsuppgift3\Inlamningsuppgift3\Inlamning3

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app      

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'web-inlamningsuppgift3-we'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A4729704913C44BD91D85D2CA50CEDEA }}
          package: .

  smoketest:
    runs-on: windows-latest
    needs: deploy

    steps:
      - name: Test Home Page
        run: |
          $functionKey = "${{ secrets.HOMEKEY }}"
          $response = Invoke-RestMethod -Uri "https://func-smoketest.azurewebsites.net/api/HomeTest?code=$functionKey"
          if ($response -like "*failed*") {
            Write-Error "Home Page test failed: $response"
          } else {
            Write-Host "Home Page test passed: $response"
          }
        shell: pwsh

      - name: Test Weather Page
        run: |
          $functionKey = "${{ secrets.WEATHERKEY }}"
          $response = Invoke-RestMethod -Uri "https://func-smoketest.azurewebsites.net/api/WeatherTest?code=$functionKey"
          if ($response -like "*failed*") {
            Write-Error "Weather Page test failed: $response"
          } else {
            Write-Host "Weather Page test passed: $response"
          }
        shell: pwsh